# Generated by Django 4.1.7 on 2023-02-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='elementinelement',
            constraint=models.UniqueConstraint(fields=('from_elem', 'to_elem'), name='unique element in element'),
        ),
    ]
