# Generated by Django 4.1.7 on 2023-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_elementinelement_unique element in element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='include',
            field=models.ManyToManyField(blank=True, null=True, related_name='elementinelements', through='main.ElementInElement', to='main.element'),
        ),
    ]
